"""Generate a pinned requirements file for one ``poetry.lock`` group.

The collector workflows install with ``uv`` -- Poetry on a runner is slow, and
the daily release is on a clock -- but they must not carry a hand-written
package list. That list drifted once already: the volume feature added a
module-level ``import hypersync``, nobody updated the list, and two scheduled
releases died at import time (runs 34554048666 and 34667231822) while
``test.yml`` stayed green because it installed from ``pyproject.toml``.

So the list is generated from the lock instead. ``poetry.lock`` v2.1 records
the groups each package belongs to, which is all that is needed to slice the
``main`` set out of it without resolving anything.

Regenerate after any dependency change::

    poetry lock
    python scripts/export_requirements.py

``tests/test_workflow_dependencies.py`` fails if the committed file does not
match what this script produces, so a stale file is caught by CI rather than
by a broken release.
"""

import argparse
import sys
import tomllib
from pathlib import Path

#: Written at the top of the generated file so nobody hand-edits it.
HEADER = """\
# Generated by scripts/export_requirements.py -- DO NOT EDIT BY HAND.
#
# Pinned {group} dependencies, sliced out of poetry.lock. The collector
# workflows install this with `uv pip install -r` instead of a hand-written
# package list, which is how two scheduled releases once died at import time.
#
# Regenerate with:  poetry lock && python scripts/export_requirements.py
"""


def _marker_for(package: dict, group: str) -> str | None:
    """Return the environment marker a package carries for ``group``.

    Poetry writes this field two ways: a bare string when the marker applies
    to every group the package is in, or a group-keyed table when the groups
    disagree (``colorama`` is ``platform_system == "Windows"`` for ``main``
    but ``sys_platform == "win32"`` for ``dev``).

    :param package: One ``[[package]]`` entry from the lock.
    :param group: Dependency group being exported.
    :returns: The marker expression, or ``None`` if the package is
        unconditional.
    """
    markers = package.get("markers")
    if markers is None:
        return None
    if isinstance(markers, dict):
        return markers.get(group)
    return markers


def render(lock_path: Path, group: str) -> str:
    """Render the pinned requirements text for one lock group.

    Markers are preserved rather than flattened: ``pywin32`` is Windows-only
    and has no Linux wheel, so emitting it unconditionally would fail the
    install outright on the runner. A package can also appear more than once
    under different ``python_version`` markers (``numpy`` splits at 3.14), so
    entries are keyed by name *and* version.

    :param lock_path: Path to ``poetry.lock``.
    :param group: Dependency group to export, e.g. ``main``.
    :returns: Full file contents, including the generated-file header.
    """
    lock = tomllib.loads(lock_path.read_text(encoding="utf-8"))

    lines = []
    for package in lock["package"]:
        if group not in package.get("groups", []):
            continue
        entry = f"{package['name']}=={package['version']}"
        marker = _marker_for(package, group)
        if marker:
            entry += f" ; {marker}"
        lines.append(entry)

    if not lines:
        raise SystemExit(f"no packages found in lock group {group!r}")

    return HEADER.format(group=group) + "\n" + "\n".join(sorted(lines)) + "\n"


def main() -> int:
    """Write (or verify) the generated requirements file.

    :returns: Process exit code -- ``1`` under ``--check`` when the committed
        file is stale, ``0`` otherwise.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--lock", type=Path, default=Path("poetry.lock"))
    parser.add_argument("--group", default="main")
    parser.add_argument("--output", type=Path, default=Path("requirements-collector.txt"))
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed file is out of date instead of rewriting it",
    )
    args = parser.parse_args()

    rendered = render(args.lock, args.group)

    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if current != rendered:
            print(
                f"{args.output} is out of date -- run: poetry lock && "
                f"python scripts/export_requirements.py",
                file=sys.stderr,
            )
            return 1
        return 0

    args.output.write_text(rendered, encoding="utf-8")
    pinned = sum(1 for line in rendered.splitlines() if line and not line.startswith("#"))
    print(f"wrote {args.output} ({pinned} pinned packages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
